### ISSUE TITLE
Running convert_to_oc4ids on OCDS data with missing party ids errors on party_analysis, should give a warning

### ISSUE THREAD

**Issue by pindec** [open-contracting/ocdskit#158]
If I run convert_to_oc4ids on OCDS data with no party ids ([simplified example data here](https://gist.github.com/pindec/23ff9d819cc2759d23093cc490afdf25)), I get the following error instead of a warning:
```
Traceback (most recent call last):
  File "/usr/local/bin/ocdskit", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ocdskit/cli/__main__.py", line 62, in main
    command.handle()
  File "/usr/local/lib/python3.6/dist-packages/ocdskit/cli/commands/convert_to_oc4ids.py", line 33, in handle
    project = oc4ids.run_transforms(config, self.items(), project_id=project_id)
  File "/usr/local/lib/python3.6/dist-packages/ocdskit/oc4ids.py", line 70, in run_transforms
    return _run_transforms(releases, project_id, records, output, transforms_to_run)
  File "/usr/local/lib/python3.6/dist-packages/ocdskit/oc4ids.py", line 75, in _run_transforms
    state = InitialTransformState(releases, project_id, records, output)
  File "/usr/local/lib/python3.6/dist-packages/ocdskit/oc4ids.py", line 129, in __init__
    self.party_analysis()
  File "/usr/local/lib/python3.6/dist-packages/ocdskit/oc4ids.py", line 195, in party_analysis
    party["original_party"]["_new_id"] = party["party"]["id"]
KeyError: 'id'
```

**Comment by jpmckinney** [comment]
Fixed in version 0.2.13
