### ISSUE TITLE
validate: doesn't work with local schema

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocdskit#161]
steps to reproduce:

```
curl https://standard.open-contracting.org/schema/1__1__5/release-schema.json > release-schema.json
cat data.json | ocdskit validate --schema release-schema.json
```

error:

Traceback (most recent call last):
  File "/home/ddewhurst/.local/bin/ocdskit", line 8, in <module>
    sys.exit(main())
  File "/home/ddewhurst/.local/lib/python3.6/site-packages/ocdskit/cli/__main__.py", line 63, in main
    command.handle()
  File "/home/ddewhurst/.local/lib/python3.6/site-packages/ocdskit/cli/commands/validate.py", line 30, in handle
    schema = requests.get(self.args.schema).json()
  File "/home/ddewhurst/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ddewhurst/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ddewhurst/.local/lib/python3.6/site-packages/requests_cache/core.py", line 136, in request
    **kwargs
  File "/home/ddewhurst/.local/lib/python3.6/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/home/ddewhurst/.local/lib/python3.6/site-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/ddewhurst/.local/lib/python3.6/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/home/ddewhurst/.local/lib/python3.6/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'release-schema.json': No schema supplied. Perhaps you meant http://release-schema.json?

**Comment by jpmckinney** [comment]
I've updated the docs. You need to use `--schema file://release-schema.json`
