### ISSUE TITLE
Error executing the command

### ISSUE THREAD

**Issue by JArielMG** [open-contracting/ocdskit#58]
Command:
cat Documentos/json_release_package/*.json | ocdskit combine-release-packages > out.json

Error:
Traceback (most recent call last):
  File "/usr/local/bin/ocdskit", line 11, in <module>
    load_entry_point('ocdskit==0.0.2', 'console_scripts', 'ocdskit')()
  File "/usr/local/lib/python3.6/site-packages/ocdskit/cli/__main__.py", line 48, in main
    command.handle()
  File "/usr/local/lib/python3.6/site-packages/ocdskit/cli/commands/combine_release_packages.py", line 15, in handle
    package = json.loads(line, object_pairs_hook=OrderedDict)
  File "/usr/local/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3855 (char 3854)

**Comment by jpmckinney** [comment]
This is due to a JSON error, e.g.:

    echo '{"test": 1};' | ocdskit combine-release-packages

Please check that each file is valid JSON first.

**Comment by jpmckinney** [comment]
Also, is the JSON data line-delimited? If not, you may need to pipe it through `jq -crM .`
